syntax = "proto3";

package plugin;

import "google/protobuf/empty.proto";

service InfoProviderService {
    rpc GetPluginInfo (google.protobuf.Empty) returns (PluginInfo);
}

// Information about a plugin
message PluginInfo {
    string id = 1;
    string display_name = 2;
    string version = 3;

    // Each plugin exposes a list of services
    repeated Service services = 4;
}

// High-level types (movies, shows, etc.)
enum ContentType {
    MOVIE = 0;
    TV_SHOW = 1;
}

// Describes one service implemented by this plugin
message Service {
    ServiceType type = 1;

    // The providers (e.g. site IDs) that this service supports
    // e.g. ["siteA", "siteB"]
    repeated string providers = 2;
}

enum ServiceType {
    SEARCH = 0;
    SOURCE_PROVIDER = 1;
    LINK_RESOLVER = 2;
}

service SearchService {
    rpc Search (SearchRequest) returns (SearchResponse);
}

message SearchRequest {
    ContentType type = 1;
    int32 tmdb_id = 2;
    string title = 3;
}

message SearchResponse {
    repeated SearchResult results = 1;
}

message SearchResult {
    // Provider that can handle this match
    string provider_id = 1;

    // Opaque plugin-specific identifier that uniquely identifies content on that provider
    string match = 2;
}

service SourceProviderService {
    rpc GetSources (GetSourcesRequest) returns (GetSourcesResponse);
}

message GetSourcesRequest {
    ContentType type = 1;

    // provider that this request is targeting (e.g. 'siteA')
    string provider_id = 2;

    int32 tmdb_id = 3;

    // Optional search match; preferred over TMDB ID
    optional string match = 4;

    optional int32 season = 5;
    optional int32 episode = 6;

    // Link ID from a previous source provider (useful for chaining providers)
    optional string link_id = 7;
}

message GetSourcesResponse {
    repeated Source sources = 1;
}

// A single source of media content (not yet resolved)
message Source {
    // The provider that this source targets
    string provider_id = 1;

    // Link or identifier to hand to a link resolver
    string link = 2;

    // Optional human readable metadata
    optional string quality = 3;
    optional string audio = 4;
}

service LinkResolverService {
    rpc Resolve (ResolveRequest) returns (ResolveResponse);
}

message ResolveRequest {
    string provider_id = 1;
    // Link or identifier provided by a SourceProvider
    string link = 2;
}

message ResolveResponse {
    repeated ResolvedSource sources = 1;
}

message ResolvedSource {
    string provider_id = 1;
    repeated SubtitlesTrack subtitles = 2;
    repeated Thumbnail thumbnails = 3;
    repeated VideoSource video = 4;
    repeated Segments sengments = 5;
}

message SubtitlesTrack {
    string language = 1;
    string url = 2;
    optional SourceConfiguration configuration = 5;
}

message VideoSource {
    VideoSourceType type = 1;
    LinkDesignation designation = 2;
    // Final playback URL
    string url = 3;
    optional int32 width = 4;
    optional SourceConfiguration configuration = 5;
}

enum VideoSourceType {
    HLS = 0;
    DASH = 1;
    MP4 = 2;
}

enum LinkDesignation {
    STREAMING = 0;
    // Download links usually don't throttle bandwidth
    DOWNLOAD = 1;
    BOTH = 2;
}

message Thumbnail {
    string url = 1;
    float start = 2;
    float end = 3;
    optional SourceConfiguration configuration = 5;
}

message Segments {
    SegmentType type = 1;
    float start = 2;
    float end = 3;
}

enum SegmentType {
    INTRO = 0;
    CREDITS = 1;
    OTHER = 2;
}

// Configuration for accessing a source (e.g. custom headers)
message SourceConfiguration {
    map<string, string> headers = 1;
}
