syntax = "proto3";

package rocks.agin.tv.plugin;

// Information about a plugin
message PluginInfo {
    string id = 1;
    string display_name = 2;
    string version = 3;

    // Each plugin exposes a list of services
    repeated Service services = 4;
}

// High-level types (movies, shows, etc.)
enum ContentType {
    MOVIE = 0;
    TV_SHOW = 1;
}

// Describes one service implemented by this plugin
message Service {
    ServiceType type = 1;

    // The providers (e.g. site IDs) that this service supports
    // e.g. ["siteA", "siteB"]
    repeated string providers = 2;
}

enum ServiceType {
    SEARCH = 0;
    SOURCE_PROVIDER = 1;
    LINK_RESOLVER = 2;
}

service SearchService {
    rpc Search (SearchRequest) returns (SearchResponses);
}

message SearchRequest {
    ContentType type = 1;
    int32 tmdb_id = 2;
    string title = 3;
}

message SearchResponses {
    repeated SearchResult results = 1;
}

message SearchResult {
    // Provider that can handle this match
    string provider_id = 1;

    // Opaque plugin-specific identifier that uniquely identifies content on that provider
    string match = 2;
}

service SourceProviderService {
    rpc GetSources (SourceRequest) returns (SourceResponse);
}

message SourceRequest {
    ContentType type = 1;

    // provider that this request is targeting (e.g. 'siteA')
    string provider_id = 2;

    int32 tmdb_id = 3;

    // Optional search match; preferred over TMDB ID
    optional string match = 4;

    optional int32 season = 5;
    optional int32 episode = 6;
}

message SourceResponse {
    repeated Source sources = 1;
}

message Source {
    // The provider that produced this source
    string provider_id = 1;

    // Link or identifier to hand to a link resolver
    string link = 2;

    // Optional human readable metadata
    string quality = 3;
    string audio = 4;
}

service LinkResolverService {
    rpc Resolve (ResolveRequest) returns (ResolveResponse);
}

message ResolveRequest {
    string provider_id = 1;
    string link = 2;
}

message ResolveResponse {
    // Final playback URL
    string url = 1;
}
